// @name README 生成
// @description フォルダ情報をもとに README.md のテンプレートを生成

function detectStack(dirPath) {
  return (
    'powershell -Command "' +
    '$dir = \\"' + dirPath + '\\";' +
    '$name = Split-Path $dir -Leaf;' +
    '$stack = @();' +
    'if (Test-Path (Join-Path $dir \\"package.json\\"))   { $stack += \\"Node.js\\" };' +
    'if (Test-Path (Join-Path $dir \\"go.mod\\"))         { $stack += \\"Go\\" };' +
    'if (Test-Path (Join-Path $dir \\"build.zig\\"))      { $stack += \\"Zig\\" };' +
    'if (Test-Path (Join-Path $dir \\"Cargo.toml\\"))     { $stack += \\"Rust\\" };' +
    'if (Test-Path (Join-Path $dir \\"requirements.txt\\")) { $stack += \\"Python\\" };' +
    'if (Test-Path (Join-Path $dir \\"mix.exs\\"))        { $stack += \\"Elixir\\" };' +
    '$stackStr = if ($stack.Count -gt 0) { $stack -join \\" / \\" } else { \\"(不明)\\" };' +
    '$date = Get-Date -Format yyyy-MM-dd;' +
    '$content = @"' +
    '# $name\n\n' +
    '> プロジェクトの概要をここに書いてください。\n\n' +
    '## 技術スタック\n\n' +
    '$stackStr\n\n' +
    '## セットアップ\n\n' +
    '```bash\n# インストール手順をここに書いてください\n```\n\n' +
    '## 使い方\n\n' +
    '```bash\n# 使い方をここに書いてください\n```\n\n' +
    '## ライセンス\n\n' +
    'MIT\n\n' +
    '---\n' +
    '_Generated by hue on $date_\n' +
    '"@;' +
    '$path = Join-Path $dir \\"README.md\\";' +
    'if (Test-Path $path) {' +
    '  Write-Host \\"README.md は既に存在します。スキップしました。\\"' +
    '} else {' +
    '  Set-Content -Path $path -Value $content -Encoding UTF8;' +
    '  Write-Host \\"README.md を生成しました: $path\\"' +
    '}"'
  )
}

hue.contextMenu.add({
  label: 'README.md を生成',
  icon: '📝',
  match: (entry) => entry.isDir,
  action: (entry) => {
    hue.exec(detectStack(entry.path))
    setTimeout(() => hue.refresh(), 800)
  },
})

hue.contextMenu.add({
  label: 'README.md を開く',
  icon: '📖',
  match: (entry) => entry.isDir,
  action: (entry) => {
    const readme = entry.path + '\\README.md'
    hue.exec(
      'powershell -Command "' +
      'if (Test-Path \\"' + readme + '\\") {' +
      '  Start-Process notepad \\"' + readme + '\\"' +
      '} else { Write-Host \\"README.md が見つかりません\\" }"'
    )
  },
})
