// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function CopyItem(arg1, arg2) {
  return window['go']['main']['App']['CopyItem'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetParentDir(arg1) {
  return window['go']['main']['App']['GetParentDir'](arg1);
}

export function GetPreview(arg1) {
  return window['go']['main']['App']['GetPreview'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStartupPath() {
  return window['go']['main']['App']['GetStartupPath']();
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function MoveItem(arg1, arg2) {
  return window['go']['main']['App']['MoveItem'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenInNewWindow(arg1) {
  return window['go']['main']['App']['OpenInNewWindow'](arg1);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function RenameItem(arg1, arg2) {
  return window['go']['main']['App']['RenameItem'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
