// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFavorite(arg1:string):Promise<void>;

export function CopyItem(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function ExecInConsole(arg1:string,arg2:string):Promise<void>;

export function GetDrives():Promise<Array<main.DriveInfo>>;

export function GetHomeDir():Promise<string>;

export function GetParentDir(arg1:string):Promise<string>;

export function GetPreview(arg1:string):Promise<string>;

export function GetSettings():Promise<main.HueSettings>;

export function GetStartupPath():Promise<string>;

export function GetThumbnail(arg1:string):Promise<string>;

export function ListDirectory(arg1:string):Promise<Array<main.FileEntry>>;

export function MoveItem(arg1:string,arg2:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenInNewWindow(arg1:string):Promise<void>;

export function OpenSettings():Promise<void>;

export function RemoveFavorite(arg1:string):Promise<void>;

export function RenameItem(arg1:string,arg2:string):Promise<void>;

export function RunCommandShortcut(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSettings(arg1:main.HueSettings):Promise<void>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<main.SearchEntry>>;
